### PR TITLE
Upgrade to scala.js 1.0.0

### PR DESCRIPTION
**Pull request by taig**

### CODE REVIEW

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
The tests of the `enum` project are failing :(

Do you mind restoring the `Foo` and `TwoLevels` types as they were previously defined? I’m not sure what’s wrong with the changes but I can’t investigate the problem.

**Comment by taig** [comment]
Sorry, I was certain I finally got them working in the end. Will take another look.

**Comment by taig** [comment]
It should be working now; I was only testing incremental compile+test loops and never did a clean run. Leaving the test ADTs in their original position was not possible, it yielded a lot of `knownDirectSubclasses` errors after upgrading Scala. Another interesting observation: `val enum = Enum[Foo]` in `EnumSuite` suddenly also started triggering `knownDirectSubclasses` errors. I believe this has to do with initialization order and the fact that the `Enum.apply` summoner has the power to derive an instance on the fly.

**Comment by julienrf** [comment]
> `val enum = Enum[Foo]` in `EnumSuite` suddenly also started triggering `knownDirectSubclasses` errors.

This is bad. Is it a regression in the compiler or in the `enum` lib? I would like to understand why this stopped working.

**Comment by taig** [comment]
It's a regression in the compiler, only Scala 2.11 appears to be affected. There exists an [issue](https://github.com/scala/bug/issues/10330) and a [fix](https://github.com/scala/scala/pull/6029), but it doesn't look like it was backported to 2.11 because the errors exists in all version >= 2.11.9. And as the issue suggests, the problem exists for 2.12.0-2.12.3 and is fixed in 2.12.4.

```
> ++2.11.8 enumJVM/test:compile
...
[success] Total time: 2 s, completed 10.03.2020 16:33:51
> ++2.11.9 enumJVM/test:compile
...
[error] knownDirectSubclasses of Foo observed before subclass Bar registered
[error] knownDirectSubclasses of Foo observed before subclass Baz registered
[error] knownDirectSubclasses of TwoLevels observed before subclass FirstValue registered
[error] knownDirectSubclasses of TwoLevels observed before subclass SecondLevel registered
[error] four errors found
[error] (enumJVM/test:compileIncremental) Compilation failed
[error] Total time: 1 s, completed 10.03.2020 16:33:57
```

So we might as well stay on 2.11.8 and leave the tests unchanged if you prefer that.

**Comment by julienrf** [comment]
Waow, thanks a lot @Taig for the investigation. Yes I would prefer staying on 2.11.8 then if you don’t mind.

**Comment by taig** [comment]
> So we might as well stay on 2.11.8 and leave the tests unchanged if you prefer that.

Sorry, that was a bit of a quick shot. This is of course not possible because Scala.js 1.0.0 is only published for Scala 2.11.12.

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
Thanks @Taig, I’ve just published version 3.1 for Scala.js 1.x :)

**Pull request merged**
